![](Bellman.png)

In [2]:
import numpy as np
import random

In [8]:
dimensiones = (5, 5)
estado_inicial = (0, 0)
estado_objetivo = (4, 4)
obstaculos = [(1,1), (1,3), (2,3), (3,0) ]
acciones = [(-1, 0), (1,0), (0,-1), (0,1) ]

In [12]:
num_estados = dimensiones[0] * dimensiones[1]
num_estados

25

In [14]:
num_acciones = len(acciones)
num_acciones

4

In [16]:
Q = np.zeros((num_estados, num_acciones))
Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
def estado_a_indice(estado): #Devuelve en que posicion esta de la cuadricula
    return estado[0] * dimensiones[1] + estado[1]    

In [32]:
ejemplo = estado_a_indice((1, 0)) #enviamos la accion que se realizo

In [34]:
ejemplo

5

In [36]:
alpha = 0.1 #Nivel de aprendizaje, mientras mas pequeño mas lento pero seguro
gamma = 0.99 #Mejor recomenpza a largo plazo, mientras mas alto mas a futuro y a menor numero mas inmediatas
epsilon = 0.2 #Explora el entorno, variacion de caminos.No reppita siempre la misma decision
episodios = 100 #Cantidad de episodios que va a repetir 

In [40]:
def elegir_accion(estado):
    if random.uniform(0,1) < epsilon:
        return random.choice(range(num_acciones))
    else: 
        return np.argmax(Q[estado_a_indice(estado)])

In [49]:
def aplicar_accion(estado, accion_idx):
    accion = acciones[accion_idx]
    nuevo_estado = tuple(np.add(estado, accion) % dimensiones)

    if nuevo_estado in obstaculos or nuevo_estado == estado:
        return estado, -100, False
    if nuevo_estado == estado_objetivo:
        return nuevo_estado, 100, True
    return nuevo_estado, -1, False

In [53]:
for episodio in range(episodios):
    estado = estado_inicial
    terminado = False
    
    while not terminado:
        idx_estado = estado_a_indice(estado)
        accion_idx = elegir_accion(estado)
        nuevo_estado, recompensa, terminado = aplicar_accion(estado, accion_idx)
        idx_nuevo_estado = estado_a_indice(nuevo_estado)
        
        Q[idx_estado, accion_idx] = Q[idx_estado, accion_idx] + alpha + (recompensa + gamma * np.max(Q[idx_nuevo_estado]) - Q[idx_estado, accion_idx])
        
        estado = nuevo_estado

In [55]:
politica = np.zeros(dimensiones, dtype=int)
politica

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [59]:
for i in range(dimensiones[0]):
    for j in range(dimensiones[1]):
        estado = (i, j)
        idx_estado = estado_a_indice(estado)
        mejor_accion = np.argmax(Q[idx_estado])
        politica[i, j] = mejor_accion

print("Politica aprendida (0:arriba, 1:abajo, 2:izquierda, 3:derecha)")
print(politica)

Politica aprendida (0:arriba, 1:abajo, 2:izquierda, 3:derecha)
[[0 2 2 1 0]
 [0 0 2 0 0]
 [1 2 2 0 2]
 [0 0 0 1 1]
 [2 2 3 1 0]]
