# Singular Value Descomposition (SVD)

### Fórmula base
![](FormulaSVD.png)


### Ejemplo
![](a.png)![](u.png)![](sigma.png)![](vt.png)

In [25]:
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt

In [13]:
A = np.array([ [1,2], [3,4], [5,6] ])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
U , sigma, VT = np.linalg.svd(A)

In [17]:
U

array([[-0.2298477 ,  0.88346102,  0.40824829],
       [-0.52474482,  0.24078249, -0.81649658],
       [-0.81964194, -0.40189603,  0.40824829]])

In [19]:
sigma

array([9.52551809, 0.51430058])

In [21]:
VT

array([[-0.61962948, -0.78489445],
       [-0.78489445,  0.61962948]])

In [27]:
iris = load_iris()
X = iris.data

In [31]:
X_centrado = X - np.mean(X, axis=0)

In [33]:
U, sigma, VT = np.linalg.svd(X_centrado)

In [37]:
k = 2
X_transformado = U[:, :k] * sigma[:k] #Se descompone los datos para disminuir la singularidad(Que sean mas parejos)

In [39]:
especies = ["setosa","versicolor","virginica"]

In [43]:
plt.figure(figsize=(8,6))
for i in range(3):
    plt.scatter(X_transformado[iris.target == i, 0],
                X_transformado[iris.target == i, 1],
                label=especies[i]
                )
plt.xlabel("Componente Principial 1")
plt.ylabel("Componente Principial 2")
plt.legend()
plt.title("Dataset iris transformado por SVD");