In [14]:
import numpy as np

In [16]:
array1d = np.array([1, 2, 3, 4, 5])

In [18]:
array2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

In [26]:
array1d[-1]

5

In [28]:
array2d[0]

array([1, 2, 3])

In [34]:
array2d[1][2]

6

In [36]:
array2d[1,2]

6

In [38]:
array1d[1:4]

array([2, 3, 4])

In [40]:
array2d[1,:]

array([4, 5, 6])

In [42]:
array2d[1,1:3]

array([5, 6])

In [46]:
array2d[:,1]

array([2, 5, 8])

In [48]:
array2d[:2, :2]

array([[1, 2],
       [4, 5]])

In [50]:
array1d > 3

array([False, False, False,  True,  True])

In [52]:
array2d > 3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [54]:
array2d % 2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])