In [2]:
import numpy as np

In [3]:
array1 = np.array([1, 2, 3])
array1

array([1, 2, 3])

In [4]:
array2 = np.array([[0], [10], [20], [30]])
array2

array([[ 0],
       [10],
       [20],
       [30]])

In [8]:
broadcast_suma = array2 + array1
broadcast_suma

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [10]:
broadcast_multi = array2 * array1
broadcast_multi

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [16]:
resultado = np.add(a,b)
resultado

array([5, 7, 9])

In [26]:
resultado1 = np.subtract(a, b)
resultado1

array([-3, -3, -3])

In [30]:
resultado2 = np.multiply(a, b) #Multiplicacion
resultado2

array([ 4, 10, 18])

In [32]:
resultado3 = np.divide(a, b) #Division
resultado3

array([0.25, 0.4 , 0.5 ])

In [36]:
resultado4 = np.exp(a) #Exponencial
resultado4

array([ 2.71828183,  7.3890561 , 20.08553692])

In [38]:
resultado5 = np.log(a) #Logaritmo base
resultado5

array([0.        , 0.69314718, 1.09861229])

In [40]:
resultado6 = np.log2(a) #Logaritmo base 2,si le agregamos u numero al lado del log lo agregamos
resultado6

array([0.       , 1.       , 1.5849625])

In [42]:
resultado7 = np.sqrt(a) #Raiz cuadrada
resultado7

array([1.        , 1.41421356, 1.73205081])