In [4]:
import numpy as np

In [6]:
array = np.array([1,2,np.nan,4,5])
array

array([ 1.,  2., nan,  4.,  5.])

In [8]:
np.isnan(array)

array([False, False,  True, False, False])

In [10]:
np.mean(array)

nan

In [12]:
np.nanmean(array) #Ignor al numero no valido!

3.0

In [22]:
array_con_0 = np.where(np.isnan(array), 0, array) #Nos muestra donde esta el 0
array_con_0

array([1., 2., 0., 4., 5.])

In [32]:
promedio = np.nanmean(array)
array_con_promedio = np.where(np.isnan(array), promedio, array)
array_con_promedio

array([1., 2., 3., 4., 5.])

In [36]:
array_filtrado = array[~np.isnan(array)] #Simoblo Alt 126
array_filtrado

array([1., 2., 4., 5.])